/*
* Name              : RecordDMLConstantUtility
* Description       : Constant utility class for Record DML
* Created           : 4th March 2026
* ------------------------- Change History -----------------------------
* Change Type       : Created
* Change Date       : 4th March 2026
* Change Description: Created
*/
public with sharing class RecordDMLConstantUtility {
    public static final String dmlInsert = 'INSERT';
    public static final String dmlUpdate = 'UPDATE';
    public static final String dmlDelete = 'DELETE';
}